# Generated by Django 5.0.7 on 2024-07-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_custem_costumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='server',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
